name: mlops-training-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
      - pandas
      - numpy
      - scikit-learn
      - xgboost
      - azureml-core
      - mlflow
